model_provider = "mobiusdefault"
model = "gpt-5.5"
model_reasoning_effort = "xhigh"
network_access = "enabled"
disable_response_storage = true
windows_wsl_setup_acknowledged = true
model_verbosity = "high"

[model_providers.mobiusdefault]
name = "mobiusdefault"
base_url = "https://xxxx.xxxx/xxxx/v1"
wire_api = "responses"
env_key = "XXXX_API_KEY"
api_key = "replace-me-auth-token"

[tui.model_availability_nux]
"gpt-5.5" = 4

[features]
apps = false
enable_mcp_apps = false