import assert from 'node:assert/strict'
import fs from 'node:fs'

const read = relative => fs.readFileSync(new URL(relative, import.meta.url), 'utf8')

const markdownService = read('../src/services/markdown.ts')
const fileTarget = read('../src/components/code-artifacts/file-target.ts')
const fileLink = read('../src/components/code-artifacts/FileReferenceLink.tsx')
const codeBlock = read('../src/components/code-artifacts/CodeBlock.tsx')
const codeMarkdown = read('../src/components/code-artifacts/CodeMarkdownComponents.tsx')
const preview = read('../src/components/code-artifacts/FilePreviewLayer.tsx')
const sessionPanel = read('../src/components/session-jsonl-panel.tsx')
const chat = read('../src/components/chat.tsx')
const assistant = read('../src/components/assistant-chat.tsx')
const compactMarkdown = read('../src/components/jsonl-compact-markdown.tsx')
const writePreview = read('../src/components/viewer/WritePreview.tsx')
const readCards = read('../src/components/viewer/ReadCards.tsx')
const diff = read('../src/components/viewer/CodeDiff.tsx')
const diffRows = read('../src/components/code-git/DiffRows.tsx')
const gitChangesViewer = read('../src/components/code-git/GitChangesViewer.tsx')
const gitTypes = read('../src/components/code-git/types.ts')
const toolContext = read('../src/components/session-tool-context.ts')
const codeMirror = read('../src/components/workspace/code-mirror-editor.tsx')
const codeConversation = read('../src/components/workspace/code-conversation-pane.tsx')
const vscodeLink = read('../src/components/jsonl-vscode-link.tsx')
const projectFiles = read('../src/components/project-files.tsx')
const issuePage = read('../src/pages/IssuePage.tsx')
const researchPage = read('../src/pages/ResearchPage.tsx')
const styles = read('../src/index.css')

assert.match(markdownService, /remarkFileTargets/, 'markdown must register the shared file-target remark plugin')
assert.match(fileLink, /event\.preventDefault\(\)/, 'file chips must always suppress browser navigation')
assert.doesNotMatch(fileLink, /window\.open/, 'file chips must not open VSCode or browser tabs by default')
assert.match(fileLink, /message-file-link__basename/, 'file chips must show the basename')
assert.match(fileLink, /message-file-link__line/, 'file chips must show a structured line label')

assert.match(codeBlock, /code-block-header__language/, 'a target-less code header must still render its language')
assert.match(codeBlock, /copySource !== undefined[\s\S]*code-block-header__copy/, 'a target-less code header must still render copy when code is supplied')
assert.match(codeBlock, /target && <FileReferenceLink target=\{target\}/, 'a code header must render a file chip only for an explicit target')
assert.match(codeBlock, /data-code-target=\{target \? 'present' : 'absent'\}/, 'code headers must expose their target/no-target contract')
assert.match(codeBlock, /document\.execCommand\('copy'\)/, 'code copy must retain a clipboard fallback')
assert.match(codeBlock, /copyState === 'error'/, 'code copy failure must have visible feedback')
assert.match(codeMarkdown, /pre: MarkdownCodeBlock as any/, 'all shared Markdown renderers must use the common fence header')
assert.doesNotMatch(assistant, /const CodePre/, 'Assistant Markdown must not keep its own fence renderer')
assert.match(assistant, /components=\{CODE_MARKDOWN_COMPONENTS\}/, 'Assistant Markdown must use the shared components')
assert.match(compactMarkdown, /\.\.\.CODE_MARKDOWN_COMPONENTS/, 'Easy/JSONL Markdown must use the shared components')
for (const [name, source] of [['Assistant', assistant], ['Easy/JSONL', compactMarkdown], ['legacy Chat', chat]]) {
  assert.doesNotMatch(source, /(?:function|const)\s+(?:MarkdownAnchor|CodePre)\b/, `${name} must not keep a local Markdown anchor/fence renderer`)
}
assert.match(writePreview, /<CodeBlockHeader[\s\S]*target=\{target\}/, 'Write headers must pass their trusted tool target to the shared header')
assert.match(readCards, /<CodeBlockHeader[\s\S]*target=\{rangedTarget\}/, 'Read headers must pass their trusted tool target to the shared header')
assert.match(diff, /<CodeBlockHeader[\s\S]*target=\{target\}/, 'Edit headers must pass their trusted tool target to the shared header')

assert.match(sessionPanel, /CodeArtifactOpenProvider onOpenArtifact=\{onOpenArtifact\}/, 'the JSONL panel must only dispatch artifact requests to its Chat host')
assert.doesNotMatch(sessionPanel, /VSCodeOpenProvider/, 'the JSONL panel must no longer default file clicks to VSCode')
assert.match(preview, /\/api\/projects\/\$\{encodeURIComponent\(projectId\)\}\/file\?path=/, 'preview must use the existing read-only project file API')
assert.match(preview, /role="dialog"[\s\S]*aria-modal="false"/, 'preview must stay a complementary dialog so chat remains readable')
assert.match(preview, /useWorkbenchShellSlot\('preview'\)/, 'preview must occupy the workbench preview slot when the shell is present')
assert.match(preview, /createPortal\(panel, previewSlot\)/, 'preview must portal into the stable preview slot without remounting chat')
assert.match(preview, /workspaceTabKey|data-code-artifact-workspace/, 'preview must keep multiple files as workspace tabs')
assert.match(preview, /filePathSegments|code-artifact-preview__crumb/, 'preview must show a breadcrumb for the active file')
assert.match(preview, /<FileWorkspaceTree/, 'preview must keep a synced project file tree beside the file')
assert.match(fileTarget, /export function workspaceTabKey/, 'workspace tabs must key off the project-relative path')
assert.match(fs.readFileSync(new URL('../src/components/code-artifacts/FileWorkspaceTree.tsx', import.meta.url), 'utf8'), /筛选文件/, 'the workspace tree must provide a file filter')
assert.match(fs.readFileSync(new URL('../src/components/code-artifacts/FileWorkspaceTree.tsx', import.meta.url), 'utf8'), /ancestorDirs|selectedAbsPath/, 'the workspace tree must expand ancestors and highlight the active file')
assert.match(preview, /code-artifact-layer--docked/, 'preview must fall back to a docked pane outside the workbench shell')
assert.doesNotMatch(preview, /code-artifact-layer__backdrop/, 'preview must not render a dimming or blur backdrop')
assert.doesNotMatch(styles, /\.code-artifact-layer__backdrop/, 'preview styles must not keep a full-screen blur overlay')
assert.doesNotMatch(styles, /\.code-artifact-(?:layer|preview)[^{]*\{[^}]*backdrop-filter/, 'preview must not blur the conversation')
assert.match(preview, /event\.key !== 'Escape'/, 'preview must close on Escape')
assert.match(preview, /重新读取[\s\S]*复制路径[\s\S]*关闭预览/, 'preview errors must keep retry, copy-path and close actions in place')
assert.match(preview, /该引用不是当前项目中的文件[\s\S]*右侧项目文件/, 'missing files must explain likely causes and point to the workspace tree')
assert.match(preview, /sanitizeToolError[\s\S]*safeToolPathLabel\(activeRequest\.target\.path\)/, 'preview errors must redact unresolved absolute paths')
assert.match(preview, /next\[index\] \|\| next\[index - 1\]/, 'closing the active tab must prefer the right neighbor')
assert.match(preview, /setRevealDir\(crumb\.path\)/, 'breadcrumb folders must reveal the matching tree directory')
assert.match(preview, /code-artifact-preview__line--target/, 'preview must highlight the requested line range')
assert.match(preview, /onPointerDown=\{event => selectLine/, 'preview must support direct line selection')
assert.match(preview, /event\.shiftKey[\s\S]*selectionAnchorRef/, 'preview must support Shift+click ranges')
assert.match(preview, /onPointerEnter=\{event => extendSelection/, 'preview must support dragged line ranges')
assert.match(preview, /formatCodeReference\(currentPath, language, lines, selectedRange\)/, 'preview must insert a ranged path and snippet')
assert.match(preview, /highlightFileLines|data-code-artifact-highlighted/, 'preview must syntax-highlight file contents')
assert.match(fs.readFileSync(new URL('../src/components/code-artifacts/highlight-file-lines.ts', import.meta.url), 'utf8'), /highlight\.js\/lib\/common/, 'preview highlighting must load the official common language set')
assert.match(fs.readFileSync(new URL('../src/components/code-artifacts/CodeBlock.tsx', import.meta.url), 'utf8'), /BASENAME_LANGUAGE[\s\S]*dockerfile[\s\S]*makefile/, 'path language detection must recognize extensionless repo files')
assert.match(preview, /在编辑器打开/, 'editor opening must remain an explicit preview action')
assert.match(preview, /code-artifact-preview__tab-actions/, 'preview actions must stay in the compact tab row')
assert.doesNotMatch(preview, /code-artifact-preview__meta/, 'preview must not repeat filename metadata pills under the tabs')
assert.match(preview, /onOpenEditor\(selectedRange[\s\S]*withFileTargetRange/, 'preview must pass its selected line/range to a location-capable internal editor')
assert.match(preview, /在 VSCode Web 打开文件/, 'external VSCode copy must only promise to open the file')
assert.doesNotMatch(preview, /VSCode[^'"`\n]*(?:跳行|定位到)/, 'external VSCode copy must not claim reliable line positioning')
assert.match(preview, /event\.stopImmediatePropagation\(\)/, 'preview Escape must stop at the top layer')
assert.match(preview, /trigger\?\.isConnected[\s\S]*fallbackFocusRef/, 'preview must restore its trigger or message-container fallback')
assert.match(styles, /@media \(max-width: 767px\)[\s\S]*height: min\(88dvh, 880px\)/, 'narrow preview must become a bottom sheet')
assert.match(styles, /scroll-margin-block: 4\.5rem/, 'target rows must clear the sticky preview chrome')
assert.match(styles, /\.code-artifact-preview \.hljs-keyword/, 'preview syntax colors must reuse the shared syntax tokens')

assert.match(chat, /artifactOpenRequest[\s\S]*fileChangesRequest/, 'Chat must own preview and diff targets without remounting the message list')
assert.match(chat, /document\.execCommand\('insertText', false, insertion\)/, 'Composer references must retain native undo when available')
assert.match(chat, /onInsertReference=\{insertArtifactReference\}/, 'preview references must return through the Chat host')
assert.doesNotMatch(chat, /function SessionFileChangesModal/, 'the legacy file-changes implementation must leave chat.tsx')
assert.match(chat, /<GitChangesViewer[\s\S]*initialPath=\{fileChangesRequest\.target\?\.path\}/, 'the existing modal entry must now render the extracted viewer with its initial path')
assert.match(chat, /artifactAboveChanges[\s\S]*suspended=\{artifactAboveChanges\}[\s\S]*setArtifactAboveChanges\(true\)/, 'preview and Git viewer must preserve their overlay source stack')
assert.match(gitTypes, /original_paths[\s\S]*sessionFileMatches/, 'diff initial-path matching must include original paths')
assert.match(gitChangesViewer, /该文件不是本会话修改[\s\S]*返回文件预览/, 'a path outside the session list must explain and return to preview')
assert.match(gitChangesViewer, /\['unstaged', 'staged'\][\s\S]*role="tab"/, 'the viewer must expose explicit unstaged/staged source tabs in that order')
assert.match(gitChangesViewer, /features\/git-diff\?file=.*&mode=\$\{mode\}/, 'every viewer diff request must include the selected mode')
assert.match(gitChangesViewer, /tabIndex=\{focusIndex === index \? 0 : -1\}/, 'the file list must use roving tabindex')
for (const key of ['ArrowDown', 'ArrowUp', 'Home', 'End', 'Enter']) {
  assert.match(gitChangesViewer, new RegExp(`event\\.key === '${key}'`), `the file list must implement ${key}`)
}
assert.match(gitChangesViewer, /if \(selection\)[\s\S]*setSelection\(null\)[\s\S]*return[\s\S]*exit\(\)/, 'Escape must clear a Diff selection before leaving the viewer')
assert.match(gitChangesViewer, /本会话改过，但当前工作树无该 diff[\s\S]*不会自动回退到最近 commit/, 'an old Session file with no current diff must keep the P1 source boundary explicit')
assert.match(gitChangesViewer, /重试当前 Diff[\s\S]*重试当前来源/, 'diff errors and empty diffs must both retry in place')
assert.match(gitChangesViewer, /sourceLabel[\s\S]*git-changes-viewer--suspended/, 'the viewer must keep its source while another tool layer is above it')
assert.match(gitChangesViewer, /trigger\?\.isConnected[\s\S]*fallbackFocusRef/, 'leaving the viewer must restore its trigger or the Chat fallback')
assert.match(diffRows, /parseUnifiedDiff[\s\S]*oldLine[\s\S]*newLine/, 'the shared parser must model real old/new source lines')
assert.match(diffRows, /kind: 'meta'[\s\S]*oldLine: null, newLine: null/, 'raw diff metadata must never receive fake source line numbers')
assert.match(diffRows, /targetFromTrustedPath\(path, \{ intent: 'preview', source: 'diff' \}\)/, 'Diff hunks and source lines must use artifact targets')
assert.doesNotMatch(diff, /function CodeDiffRows/, 'JSONL Edit must not keep a local Diff row renderer')
assert.match(diff, /<DiffRows model=\{model\} fallbackPath=\{file\.filePath\}/, 'JSONL Edit must render rows through the shared DiffRows component')
for (const state of ['二进制文件变更', '文件已重命名', '新文件记录', '删除文件记录', '文件元数据']) {
  assert.match(diffRows, new RegExp(state), `the Diff renderer must explain the ${state} no-hunk state`)
}
assert.match(gitChangesViewer, /<FileReferenceLink target=\{selectedTarget\}/, 'the selected file header must use an artifact target')
assert.match(diff, /intent: 'diff'[\s\S]*source: 'jsonl-tool'/, 'JSONL Edit file headers must open the existing session diff')
assert.match(toolContext, /isAbsoluteToolPath[\s\S]*return basename[\s\S]*sanitizeToolError/, 'tool object context must not expose unresolved absolute paths')

assert.match(codeConversation, /initialFilePath[\s\S]*initialLine[\s\S]*initialEndLine/, 'CodeConversation must accept an initial file and line range')
assert.match(codeConversation, /normalizeInitialProjectFile[\s\S]*onSelectFile\(entry, location\)/, 'CodeConversation must open the explicit initial project file through its existing read path')
assert.match(codeConversation, /initialLine=\{initialEditorLocation\?\.line\}[\s\S]*initialEndLine=\{initialEditorLocation\?\.endLine\}/, 'CodeConversation must pass the location to CodeMirror')
assert.match(codeMirror, /onCreateEditor=\{captureEditorView\}/, 'CodeMirror must retain its actual EditorView')
assert.match(codeMirror, /editorView\.dispatch\([\s\S]*selection[\s\S]*EditorView\.scrollIntoView/, 'CodeMirror must dispatch selection and scrollIntoView after the view exists')
assert.match(codeMirror, /initialLocationKey/, 'reopening the same range must be able to retrigger editor positioning')
assert.match(chat, /supportsFileLocation[\s\S]*onOpenEditor=\{workspaceEditor\?\.available/, 'the artifact host must only pass targets to editors that declare reliable location support')
for (const [name, source] of [['Issue', issuePage], ['Research', researchPage]]) {
  assert.match(source, /supportsFileLocation: true/, `${name} CodeConversation host must declare reliable file location support`)
  assert.match(source, /initialFilePath=\{codeEditorRequest\?\.target\.path\}[\s\S]*initialOpenKey=\{codeEditorRequest\?\.requestKey\}/, `${name} must pass the artifact target into CodeConversation`)
}
assert.match(fileTarget, /stripFileTargetLocation[\s\S]*splitLocation/, 'VSCode file payloads must reuse the shared hash/colon location parser')
assert.match(projectFiles, /stripVscodeFileLocation[\s\S]*stripFileTargetLocation/, 'VSCode file opens must remove structured locations before building payloads')
assert.match(projectFiles, /这里只承诺打开文件/, 'the VSCode payload contract must explicitly limit itself to opening files')
assert.match(vscodeLink, /only promises to open a file/, 'the legacy JSONL VSCode resolver must not claim line navigation')

console.log('code artifact contract tests passed')
